### ISSUE TITLE
UI Review Refactoring

### ISSUE THREAD

**Issue by tobiasxschmidt** [DeusGmbH/XCusatio-General#73]
Zuletzt generierte Ausreden
- Scroll-Leiste nach oben verschieben
- Ausredenanzahl sollte beschränkt sein, sonst Anzeige überladen
- Schrift zuletzt generierter Ausreden relativ statt absolut bzw. Textboxgröße anpassen

Farben
- Buttons blau anpassen, damit weniger kräftig

Editor
- Textbox der Wildcards mit "Wildcards" beschirften
- Tags alphabetisch sortiert anzeigen
- Hints in leere Textfelder einfügen
- Vorlesung/Dozent + und - statt hinzufügen und entfernen
- Pfeile bei Tags hinzufügen/entfernen durch + und - ersetzen
- AGE_UNDER_18 tag bei Dozenten rausfiltern?
- Schriftart des inaktiven Tabs leicht ausgrauen

Profil
- Button für Werkseinstellungen
- Authorisieren grün, wieder entfernen rot
- Hints für Textfelder

**Comment by tobiasxschmidt** [comment]
@PascalSchroederDE 
Du hast folgende sachen noch nicht implementiert:
- Textbox der Wildcards mit "Wildcards" beschirften
- Rechsklick in ein Textfeld öffnen ein dropdown menu, welches noch nicht die richtigen styles hat
- Doppelklick zum verschieben eines tags in die andere liste im Editor
- Wenn ein neuer Dozent hinzugefügt wird, sollten auch der Name des Dozenten leer sein. 
- Beim speichern eines Dozenten überprüfen ob mindestens der Name vorhanden ist. Sonst einfach keine speicheraktion durchführen
- In den Profileinstellungen sollte nicht "Standort" stehen sondern sowas wie "Wohnort" oder "Heimatsadresse" oder so. Standort hört sich eher nach der Adresse der Uni an. Außerdem bitte das Label nicht in der Mitte von Str. Hausnr. Stadt und plz sonder direkt vor Straße, also weiter nach oben

**Comment by PascalSchroederDE** [comment]
Wildcards Label wurde nicht hinzugefügt, da zu umständlich zum momentanen Zeitpunkt
